version: '3.8'

services:
  flight-iq:
    build:
      context: .
      dockerfile: Dockerfile
    image: flight-iq-app:latest
    container_name: flight_iq_container
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
